services:
  app:
    container_name: ${CONTAINER_NAME}
    build:
      context: ./docker
    volumes:
      - ./src:/var/www/html
      - ./web:/usr/share/nginx/html
    ports:
      - '${HOST_PORT}:80'
    working_dir: /var/www/html
    environment:
      - COMPOSER_AUTH=
    tty: true
