version: '3.5'

services:
  app:
    build:
      context: ./docker
    volumes:
      - ./src:/var/www/html
      - ./sites-enabled:/etc/apache2/sites-enabled
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
    working_dir: /var/www/html
    environment:
      - COMPOSER_AUTH=
    command: >
      bash -c "apache2-foreground && \
              chown 1000:1001 -R /var/www/html"
    tty: true